### ISSUE TITLE
[Bug] game keeps randomly freezing

### ISSUE THREAD

**Issue by Mr-Squid42** [pagefaultgames/pokerogue#5649]
### Describe the bug

i'll try to describe the problem as much as possible:
the game tab freezes and then the tab becomes blank

things i know:

- seems to be able happen at any time during gameplay, can happen during early or late stages of the game
- sometimes it can be quite along time before it happens, it can end up happening once in a match or it could end up happening several times in a row
- i have to reload the tab, though once i was able to wait a bit and it came back
- it seems to be happening less often if i wait a few seconds between each input

things i don't know:
- what exactly is causing this problem from a user perspective
- if this is a firefox only issue, because i've forgotten my login details so i haven't been able to test it out on other browsers

### Reproduction

just general gameplay

### Expected behavior

for it not to freeze up

**Comment by JustinJayL** [comment]
This has been happening to me too. I believe it is the same bug. It happens on Firefox, I've tried logging in to firefox developer edition, and firefox for android as well. The issue recurs there as well.

I've attached my user and session data export. The crash is random, but occurs on multiple devices and platforms. You need to load it up (In firefox, i'm assuming) and play for usually less than 20 stages. I haven't been able to make the crash happen in chrome. This crash also makes my entire firefox session hang for a second or so.

Let me know if you'd like anything else from me.

I've opened my browser console, and this shows up in the log:

`TypeError: this.scene is undefined
    setTexture https://pokerogue.net/assets/index-C51Hle0P.js:1326
    updateInfo https://pokerogue.net/assets/loading-scene-o8SvvBua.js:1
    updateInfo https://pokerogue.net/assets/loading-scene-o8SvvBua.js:1
    updateInfo https://pokerogue.net/assets/loading-scene-o8SvvBua.js:857
    resetSummonData https://pokerogue.net/assets/loading-scene-o8SvvBua.js:857
    leaveField https://pokerogue.net/assets/loading-scene-o8SvvBua.js:857
    aE https://pokerogue.net/assets/loading-scene-o8SvvBua.js:295
    aE https://pokerogue.net/assets/loading-scene-o8SvvBua.js:295
    PQ https://pokerogue.net/assets/loading-scene-o8SvvBua.js:292
[index-C51Hle0P.js:6493:150003](https://pokerogue.net/assets/index-C51Hle0P.js)
    <anonymous> https://pokerogue.net/assets/index-C51Hle0P.js:6493
Uncaught (in promise) TypeError: this.scene is undefined
    setTexture https://pokerogue.net/assets/index-C51Hle0P.js:1326
    updateInfo https://

pokerogue.net/assets/loading-scene-o8SvvBua.js:1
    updateInfo https://pokerogue.net/assets/loading-scene-o8SvvBua.js:1
    updateInfo https://pokerogue.net/assets/loading-scene-o8SvvBua.js:857
    resetSummonData https://pokerogue.net/assets/loading-scene-o8SvvBua.js:857
    leaveField https://pokerogue.net/assets/loading-scene-o8SvvBua.js:857
    aE https://pokerogue.net/assets/loading-scene-o8SvvBua.js:295
    aE https://pokerogue.net/assets/loading-scene-o8SvvBua.js:295
    PQ https://pokerogue.net/assets/loading-scene-o8SvvBua.js:292`

[pokerogue_data.zip](https://github.com/user-attachments/files/19727870/pokerogue_data.zip)

**Comment by fishsicles** [comment]
I also have this or a similar issue running a local instance. Audio appears to still be playing and still responds to keyboard inputs, so it's not a full freeze. The last thing I see in my browser log is "Start Phase CommandPhase [battle-scene.ts:2809:14](http://localhost:8000/src/battle-scene.ts)", but when I go and make additional inputs, it gives me

> WebGL warning: texImage: Implementation bug, please file at https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Canvas%A+WebGL! ExplicitUnpacking failed: UNPACK_SKIP_PIXELS + width > UNPACK_ROW_LENGTH. 

My first thought was a graphics driver issue, but I've updated and it still seems to be happening - it may be something on Firefox's end?

**Comment by JustinJayL** [comment]
I've been trying to figure it out myself as well (Not a web dev), one thing that sometimes makes the crash happen as well is repeatedly pressing all of the arrow keys at the same time on the move selection screen. 

This reproduction method appears to only work with certain pokemon, for me, an origin form giratina with 4 moves. 

It also still crashes when I disable hardware acceleration.

**Comment by fishsicles** [comment]
I'm almost certain that the bug is related to text or window scaling. The attached session data almost never crashes at my normal resolution (1920*927 including the border but not the address bar/tabs/etc, 1617*910 active game area), but simply having the browser console open (which rescales the whole window to 1920*603, game to 1072*603) almost guarantees the crash when attempting to select Sparkling Aria on Lilligant.
[sessionData_Guest(1).prsv.txt](https://github.com/user-attachments/files/19931590/sessionData_Guest.1.prsv.txt)

**Comment by yjugl** [comment]
Hi everyone, thank you all for documenting this issue. We at Mozilla believe that this was caused by a bug on our end, which we introduced in Firefox 137 and have now fixed with the release of Firefox 139.0.4 (and your reports were super helpful in that regard!). Could you confirm that the issue no longer occurs? Thank you!

**Comment by ThatGitMITZE** [comment]
I updated my installation of Firefox and can't seem to proc any of the issues anymore myself; [I created a post on the subreddit](https://www.reddit.com/r/pokerogue/comments/1l92cbp/attention_firefox_users/) informing of the possible fix and for people to complain in if they're still having issues after updating.

**Comment by yjugl** [comment]
Thank you @ThatGitMITZE! In your new Reddit thread you mention that you have reported the bug yourself previously but we incorrectly marked it as not being something we can act upon. Could you point me to that bug report so we can reflect on what went wrong there?

**Comment by ThatGitMITZE** [comment]
@yjugl Ah, no, you misunderstand; the _game_ (PokéRogue) devs said that they thought it was something on Firefox's end at some point relatively shortly after the problems started happening and people started complaining to them about it ([I think this is the post I was remembering?](https://www.reddit.com/r/pokerogue/comments/1js88ti/game_isnt_working_on_firefox/)); I reported the site (https://pokerogue.net/) as broken some time after that, can't remember exactly when but it probably would've been over a month ago at this point.

**Comment by yjugl** [comment]
I see @ThatGitMITZE, so what happened is that your report didn't get attention? That's still not ideal but at least a bit better than my initial understanding. Thanks for clarifying.

**Comment by ThatGitMITZE** [comment]
So far I've seen exactly one person speaking up about still having issues (in the reddit post I made, at least); waiting to get confirmation that they updated to the newest Firefox version.

**Comment by ThatGitMITZE** [comment]
That one person posted about their issues in the thread, they say they're on the latest update but the issues they're describing sound different than for what this issue was made for, so this can probably be closed as fixed as this point.
